### ISSUE TITLE
Compile errors with Mastodon 4.3 branch

### ISSUE THREAD

**Issue by vmstan** [nileane/TangerineUI-for-Mastodon#69]
Logs are from fresh Docker container image being built against latest 4.3.0-alpha.0 code.

```
53.79 Entrypoint tangerine-ui = css/common-a729b6b0.css js/common-0bc45c6a5c8cd9db614d.js css/common-a729b6b0.css.map js/common-0bc45c6a5c8cd9db614d.js.map js/tangerine-ui-bd16c40b21a8bfdc4f6e.chunk.js js/tangerine-ui-bd16c40b21a8bfdc4f6e.chunk.js.map
53.79 Entrypoint tangerine-purple-ui = css/common-a729b6b0.css js/common-0bc45c6a5c8cd9db614d.js css/common-a729b6b0.css.map js/common-0bc45c6a5c8cd9db614d.js.map js/tangerine-purple-ui-3cd041e98fa3cea8e149.chunk.js js/tangerine-purple-ui-3cd041e98fa3cea8e149.chunk.js.map
53.79  [122] ./app/javascript/packs/public-path.js 877 bytes {0} [built]
53.79  [988] ./app/javascript/packs/sign_up.js 672 bytes {595} [built]
53.79 [1167] ./app/javascript/packs/remote_interaction_helper.ts 3.6 KiB {593} [built]
53.79 [1170] ./app/javascript/packs/error.js 247 bytes {444} [built]
53.79 [1281] ./app/javascript/packs/admin.jsx 8.74 KiB {437} [built]
53.79 [1283] ./app/javascript/styles/application.scss 50 bytes {442} [built]
53.79 [1284] ./app/javascript/styles/contrast.scss 50 bytes {441} [built]
53.79 [1285] ./app/javascript/styles/mastodon-light.scss 50 bytes {581} [built]
53.79 [1286] ./app/javascript/styles/mastodon-bird-ui-dark.scss 50 bytes {579} [built]
53.79 [1287] ./app/javascript/styles/mastodon-bird-ui-light.scss 50 bytes {580} [built]
53.79 [1288] ./app/javascript/styles/mastodon-bird-ui-contrast.scss 50 bytes {578} [built]
53.79 [1289] ./app/javascript/styles/tangerineui.scss 2.98 KiB {597} [built] [failed] [1 error]
53.79 [1290] ./app/javascript/styles/tangerineui-purple.scss 2.98 KiB {596} [built] [failed] [1 error]
53.79 [1296] ./app/javascript/packs/application.js + 28 modules 72.2 KiB {438} [built]
53.79        | ./app/javascript/packs/application.js 267 bytes [built]
53.79        | ./app/javascript/mastodon/main.jsx 1.22 KiB [built]
53.79        | ./app/javascript/mastodon/containers/mastodon.jsx 2.85 KiB [built]
53.79        | ./app/javascript/mastodon/performance.js 868 bytes [built]
53.79        | ./app/javascript/mastodon/features/ui/index.jsx 19.1 KiB [built]
53.79        | ./app/javascript/mastodon/features/picture_in_picture/index.jsx 1.52 KiB [built]
53.79        | ./app/javascript/mastodon/features/ui/containers/columns_area_container.js 286 bytes [built]
53.79        | ./app/javascript/mastodon/features/ui/util/react_router_helpers.jsx 2.45 KiB [built]
53.79        | ./app/javascript/mastodon/features/account/navigation.jsx 951 bytes [built]
53.79        | ./app/javascript/mastodon/features/account/containers/featured_tags_container.js 474 bytes [built]
53.79        |     + 19 hidden modules
53.79 [1297] ./app/javascript/packs/share.jsx + 2 modules 2.08 KiB {594} [built]
53.79        | ./app/javascript/packs/share.jsx 685 bytes [built]
53.79        | ./app/javascript/mastodon/containers/compose_container.jsx 670 bytes [built]
53.79        | ./app/javascript/mastodon/features/standalone/compose/index.jsx 690 bytes [built]
53.79     + 1529 hidden modules
53.79
53.79 ERROR in ./app/javascript/styles/tangerineui-purple.scss
53.79 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
53.79 ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
53.79 SassError: expected "{".
53.79   ╷
53.79 1 │ 404: Not Found
53.79   │               ^
53.79   ╵
53.79   app/javascript/styles/tangerineui-purple.scss 1:15  root stylesheet
53.79     at /opt/mastodon/node_modules/webpack/lib/NormalModule.js:316:20
53.79     at /opt/mastodon/node_modules/loader-runner/lib/LoaderRunner.js:367:11
53.79     at /opt/mastodon/node_modules/loader-runner/lib/LoaderRunner.js:233:18
53.79     at context.callback (/opt/mastodon/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
53.79     at /opt/mastodon/node_modules/sass-loader/dist/index.js:62:7
53.79     at Function.call$2 (/opt/mastodon/node_modules/sass/sass.dart.js:117841:16)
53.79     at render_closure1.call$2 (/opt/mastodon/node_modules/sass/sass.dart.js:101433:12)
53.79     at _RootZone.runBinary$3$3 (/opt/mastodon/node_modules/sass/sass.dart.js:35588:18)
53.79     at _FutureListener.handleError$1 (/opt/mastodon/node_modules/sass/sass.dart.js:34113:21)
53.79     at _Future__propagateToListeners_handleError.call$0 (/opt/mastodon/node_modules/sass/sass.dart.js:34419:49)
53.79     at Object._Future__propagateToListeners (/opt/mastodon/node_modules/sass/sass.dart.js:4203:77)
53.79     at _Future._completeError$2 (/opt/mastodon/node_modules/sass/sass.dart.js:34270:9)
53.79     at _AsyncAwaitCompleter.completeError$2 (/opt/mastodon/node_modules/sass/sass.dart.js:33895:12)
53.79     at Object._asyncRethrow (/opt/mastodon/node_modules/sass/sass.dart.js:3997:17)
53.79     at /opt/mastodon/node_modules/sass/sass.dart.js:24506:20
53.79     at _wrapJsFunctionForAsync_closure.$protected (/opt/mastodon/node_modules/sass/sass.dart.js:4022:15)
53.79     at _wrapJsFunctionForAsync_closure.call$2 (/opt/mastodon/node_modules/sass/sass.dart.js:33914:12)
53.79     at _awaitOnObject_closure0.call$2 (/opt/mastodon/node_modules/sass/sass.dart.js:33908:25)
53.79     at _RootZone.runBinary$3$3 (/opt/mastodon/node_modules/sass/sass.dart.js:35588:18)
53.79     at _FutureListener.handleError$1 (/opt/mastodon/node_modules/sass/sass.dart.js:34113:21)
53.79     at _Future__propagateToListeners_handleError.call$0 (/opt/mastodon/node_modules/sass/sass.dart.js:34419:49)
53.79     at Object._Future__propagateToListeners (/opt/mastodon/node_modules/sass/sass.dart.js:4203:77)
53.79     at _Future._completeError$2 (/opt/mastodon/node_modules/sass/sass.dart.js:34270:9)
53.79     at _Future__asyncCompleteError_closure.call$0 (/opt/mastodon/node_modules/sass/sass.dart.js:34349:18)
53.79     at Object._microtaskLoop (/opt/mastodon/node_modules/sass/sass.dart.js:4259:24)
53.79     at StaticClosure._startMicrotaskLoop (/opt/mastodon/node_modules/sass/sass.dart.js:4265:11)
53.79     at _AsyncRun__scheduleImmediateJsOverride_internalCallback.call$0 (/opt/mastodon/node_modules/sass/sass.dart.js:33815:21)
53.79     at invokeClosure (/opt/mastodon/node_modules/sass/sass.dart.js:1473:26)
53.79     at Immediate.<anonymous> (/opt/mastodon/node_modules/sass/sass.dart.js:1494:18)
53.79     at process.processImmediate (node:internal/timers:478:21)
53.79
53.79 ERROR in ./app/javascript/styles/tangerineui.scss
53.79 Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
53.79 ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
53.79 SassError: expected "{".
53.79   ╷
53.79 1 │ 404: Not Found
53.79   │               ^
53.79   ╵
53.79   app/javascript/styles/tangerineui.scss 1:15  root stylesheet
53.79     at /opt/mastodon/node_modules/webpack/lib/NormalModule.js:316:20
53.79     at /opt/mastodon/node_modules/loader-runner/lib/LoaderRunner.js:367:11
53.79     at /opt/mastodon/node_modules/loader-runner/lib/LoaderRunner.js:233:18
53.79     at context.callback (/opt/mastodon/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
53.79     at /opt/mastodon/node_modules/sass-loader/dist/index.js:62:7
53.79     at Function.call$2 (/opt/mastodon/node_modules/sass/sass.dart.js:117841:16)
53.79     at render_closure1.call$2 (/opt/mastodon/node_modules/sass/sass.dart.js:101433:12)
53.79     at _RootZone.runBinary$3$3 (/opt/mastodon/node_modules/sass/sass.dart.js:35588:18)
53.79     at _FutureListener.handleError$1 (/opt/mastodon/node_modules/sass/sass.dart.js:34113:21)
53.79     at _Future__propagateToListeners_handleError.call$0 (/opt/mastodon/node_modules/sass/sass.dart.js:34419:49)
53.79     at Object._Future__propagateToListeners (/opt/mastodon/node_modules/sass/sass.dart.js:4203:77)
53.79     at _Future._completeError$2 (/opt/mastodon/node_modules/sass/sass.dart.js:34270:9)
53.79     at _AsyncAwaitCompleter.completeError$2 (/opt/mastodon/node_modules/sass/sass.dart.js:33895:12)
53.79     at Object._asyncRethrow (/opt/mastodon/node_modules/sass/sass.dart.js:3997:17)
53.79     at /opt/mastodon/node_modules/sass/sass.dart.js:24506:20
53.79     at _wrapJsFunctionForAsync_closure.$protected (/opt/mastodon/node_modules/sass/sass.dart.js:4022:15)
53.79     at _wrapJsFunctionForAsync_closure.call$2 (/opt/mastodon/node_modules/sass/sass.dart.js:33914:12)
53.79     at _awaitOnObject_closure0.call$2 (/opt/mastodon/node_modules/sass/sass.dart.js:33908:25)
53.79     at _RootZone.runBinary$3$3 (/opt/mastodon/node_modules/sass/sass.dart.js:35588:18)
53.79     at _FutureListener.handleError$1 (/opt/mastodon/node_modules/sass/sass.dart.js:34113:21)
53.79     at _Future__propagateToListeners_handleError.call$0 (/opt/mastodon/node_modules/sass/sass.dart.js:34419:49)
53.79     at Object._Future__propagateToListeners (/opt/mastodon/node_modules/sass/sass.dart.js:4203:77)
53.79     at _Future._completeError$2 (/opt/mastodon/node_modules/sass/sass.dart.js:34270:9)
53.79     at _Future__asyncCompleteError_closure.call$0 (/opt/mastodon/node_modules/sass/sass.dart.js:34349:18)
53.79     at Object._microtaskLoop (/opt/mastodon/node_modules/sass/sass.dart.js:4259:24)
53.79     at StaticClosure._startMicrotaskLoop (/opt/mastodon/node_modules/sass/sass.dart.js:4265:11)
53.79     at _AsyncRun__scheduleImmediateJsOverride_internalCallback.call$0 (/opt/mastodon/node_modules/sass/sass.dart.js:33815:21)
53.79     at invokeClosure (/opt/mastodon/node_modules/sass/sass.dart.js:1473:26)
53.79     at Immediate.<anonymous> (/opt/mastodon/node_modules/sass/sass.dart.js:1494:18)
53.79     at process.processImmediate (node:internal/timers:478:21)
53.79 Child InjectManifest:
53.79      2 assets
53.79     Entrypoint InjectManifest = sw.js sw.js.map
53.79     [20] (webpack)/buildin/global.js 472 bytes {0} [built]
53.79     [34] ./app/javascript/mastodon/service_worker/web_push_locales.js 59.7 KiB {0} [built]
53.79     [87] ./app/javascript/mastodon/service_worker/entry.js + 72 modules 212 KiB {0} [built]
53.79          | ./app/javascript/mastodon/service_worker/entry.js 2.08 KiB [built]
53.79          | ./app/javascript/mastodon/service_worker/web_push_notifications.js 6.6 KiB [built]
53.79          |     + 71 hidden modules
53.79         + 85 hidden modules
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/styles/application.scss:
53.79      22 assets
53.79     Entrypoint mini-css-extract-plugin = *
53.79      [3] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff2 123 bytes {0} [built]
53.79      [4] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff 122 bytes {0} [built]
53.79      [5] ./app/javascript/fonts/roboto/roboto-italic-webfont.ttf 121 bytes {0} [built]
53.79      [6] ./app/javascript/fonts/roboto/roboto-italic-webfont.svg 121 bytes {0} [built]
53.79      [7] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff2 121 bytes {0} [built]
53.79      [8] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff 120 bytes {0} [built]
53.79      [9] ./app/javascript/fonts/roboto/roboto-bold-webfont.ttf 119 bytes {0} [built]
53.79     [10] ./app/javascript/fonts/roboto/roboto-bold-webfont.svg 119 bytes {0} [built]
53.79     [11] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff2 123 bytes {0} [built]
53.79     [12] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff 122 bytes {0} [built]
53.79     [13] ./app/javascript/fonts/roboto/roboto-medium-webfont.ttf 121 bytes {0} [built]
53.79     [14] ./app/javascript/fonts/roboto/roboto-medium-webfont.svg 121 bytes {0} [built]
53.79     [15] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff2 124 bytes {0} [built]
53.79     [16] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff 123 bytes {0} [built]
53.79     [25] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/application.scss 854 KiB {0} [built]
53.79         + 11 hidden modules
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/styles/contrast.scss:
53.79      22 assets
53.79     Entrypoint mini-css-extract-plugin = *
53.79      [3] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff2 123 bytes {0} [built]
53.79      [4] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff 122 bytes {0} [built]
53.79      [5] ./app/javascript/fonts/roboto/roboto-italic-webfont.ttf 121 bytes {0} [built]
53.79      [6] ./app/javascript/fonts/roboto/roboto-italic-webfont.svg 121 bytes {0} [built]
53.79      [7] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff2 121 bytes {0} [built]
53.79      [8] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff 120 bytes {0} [built]
53.79      [9] ./app/javascript/fonts/roboto/roboto-bold-webfont.ttf 119 bytes {0} [built]
53.79     [10] ./app/javascript/fonts/roboto/roboto-bold-webfont.svg 119 bytes {0} [built]
53.79     [11] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff2 123 bytes {0} [built]
53.79     [12] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff 122 bytes {0} [built]
53.79     [13] ./app/javascript/fonts/roboto/roboto-medium-webfont.ttf 121 bytes {0} [built]
53.79     [14] ./app/javascript/fonts/roboto/roboto-medium-webfont.svg 121 bytes {0} [built]
53.79     [15] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff2 124 bytes {0} [built]
53.79     [16] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff 123 bytes {0} [built]
53.79     [25] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/contrast.scss 861 KiB {0} [built]
53.79         + 11 hidden modules
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/styles/mailer.scss:
53.79      16 assets
53.79     Entrypoint mini-css-extract-plugin = *
53.79      [3] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff2 123 bytes {0} [built]
53.79      [4] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff 122 bytes {0} [built]
53.79      [5] ./app/javascript/fonts/roboto/roboto-italic-webfont.ttf 121 bytes {0} [built]
53.79      [6] ./app/javascript/fonts/roboto/roboto-italic-webfont.svg 121 bytes {0} [built]
53.79      [7] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff2 121 bytes {0} [built]
53.79      [8] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff 120 bytes {0} [built]
53.79      [9] ./app/javascript/fonts/roboto/roboto-bold-webfont.ttf 119 bytes {0} [built]
53.79     [10] ./app/javascript/fonts/roboto/roboto-bold-webfont.svg 119 bytes {0} [built]
53.79     [11] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff2 123 bytes {0} [built]
53.79     [12] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff 122 bytes {0} [built]
53.79     [13] ./app/javascript/fonts/roboto/roboto-medium-webfont.ttf 121 bytes {0} [built]
53.79     [14] ./app/javascript/fonts/roboto/roboto-medium-webfont.svg 121 bytes {0} [built]
53.79     [15] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff2 124 bytes {0} [built]
53.79     [16] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff 123 bytes {0} [built]
53.79     [19] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/mailer.scss 28.5 KiB {0} [built]
53.79         + 5 hidden modules
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/styles/mastodon-bird-ui-contrast.scss:
53.79      22 assets
53.79     Entrypoint mini-css-extract-plugin = *
53.79      [3] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff2 123 bytes {0} [built]
53.79      [4] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff 122 bytes {0} [built]
53.79      [5] ./app/javascript/fonts/roboto/roboto-italic-webfont.ttf 121 bytes {0} [built]
53.79      [6] ./app/javascript/fonts/roboto/roboto-italic-webfont.svg 121 bytes {0} [built]
53.79      [7] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff2 121 bytes {0} [built]
53.79      [8] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff 120 bytes {0} [built]
53.79      [9] ./app/javascript/fonts/roboto/roboto-bold-webfont.ttf 119 bytes {0} [built]
53.79     [10] ./app/javascript/fonts/roboto/roboto-bold-webfont.svg 119 bytes {0} [built]
53.79     [11] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff2 123 bytes {0} [built]
53.79     [12] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff 122 bytes {0} [built]
53.79     [13] ./app/javascript/fonts/roboto/roboto-medium-webfont.ttf 121 bytes {0} [built]
53.79     [14] ./app/javascript/fonts/roboto/roboto-medium-webfont.svg 121 bytes {0} [built]
53.79     [15] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff2 124 bytes {0} [built]
53.79     [16] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff 123 bytes {0} [built]
53.79     [25] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/mastodon-bird-ui-contrast.scss 2.75 MiB {0} [built]
53.79         + 11 hidden modules
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/styles/mastodon-bird-ui-dark.scss:
53.79      22 assets
53.79     Entrypoint mini-css-extract-plugin = *
53.79      [3] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff2 123 bytes {0} [built]
53.79      [4] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff 122 bytes {0} [built]
53.79      [5] ./app/javascript/fonts/roboto/roboto-italic-webfont.ttf 121 bytes {0} [built]
53.79      [6] ./app/javascript/fonts/roboto/roboto-italic-webfont.svg 121 bytes {0} [built]
53.79      [7] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff2 121 bytes {0} [built]
53.79      [8] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff 120 bytes {0} [built]
53.79      [9] ./app/javascript/fonts/roboto/roboto-bold-webfont.ttf 119 bytes {0} [built]
53.79     [10] ./app/javascript/fonts/roboto/roboto-bold-webfont.svg 119 bytes {0} [built]
53.79     [11] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff2 123 bytes {0} [built]
53.79     [12] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff 122 bytes {0} [built]
53.79     [13] ./app/javascript/fonts/roboto/roboto-medium-webfont.ttf 121 bytes {0} [built]
53.79     [14] ./app/javascript/fonts/roboto/roboto-medium-webfont.svg 121 bytes {0} [built]
53.79     [15] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff2 124 bytes {0} [built]
53.79     [16] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff 123 bytes {0} [built]
53.79     [25] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/mastodon-bird-ui-dark.scss 2.74 MiB {0} [built]
53.79         + 11 hidden modules
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/styles/mastodon-bird-ui-light.scss:
53.79      22 assets
53.79     Entrypoint mini-css-extract-plugin = *
53.79      [3] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff2 123 bytes {0} [built]
53.79      [4] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff 122 bytes {0} [built]
53.79      [5] ./app/javascript/fonts/roboto/roboto-italic-webfont.ttf 121 bytes {0} [built]
53.79      [6] ./app/javascript/fonts/roboto/roboto-italic-webfont.svg 121 bytes {0} [built]
53.79      [7] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff2 121 bytes {0} [built]
53.79      [8] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff 120 bytes {0} [built]
53.79      [9] ./app/javascript/fonts/roboto/roboto-bold-webfont.ttf 119 bytes {0} [built]
53.79     [10] ./app/javascript/fonts/roboto/roboto-bold-webfont.svg 119 bytes {0} [built]
53.79     [11] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff2 123 bytes {0} [built]
53.79     [12] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff 122 bytes {0} [built]
53.79     [13] ./app/javascript/fonts/roboto/roboto-medium-webfont.ttf 121 bytes {0} [built]
53.79     [14] ./app/javascript/fonts/roboto/roboto-medium-webfont.svg 121 bytes {0} [built]
53.79     [15] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff2 124 bytes {0} [built]
53.79     [16] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff 123 bytes {0} [built]
53.79     [25] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/mastodon-bird-ui-light.scss 2.79 MiB {0} [built]
53.79         + 11 hidden modules
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/styles/mastodon-light.scss:
53.79      22 assets
53.79     Entrypoint mini-css-extract-plugin = *
53.79      [3] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff2 123 bytes {0} [built]
53.79      [4] ./app/javascript/fonts/roboto/roboto-italic-webfont.woff 122 bytes {0} [built]
53.79      [5] ./app/javascript/fonts/roboto/roboto-italic-webfont.ttf 121 bytes {0} [built]
53.79      [6] ./app/javascript/fonts/roboto/roboto-italic-webfont.svg 121 bytes {0} [built]
53.79      [7] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff2 121 bytes {0} [built]
53.79      [8] ./app/javascript/fonts/roboto/roboto-bold-webfont.woff 120 bytes {0} [built]
53.79      [9] ./app/javascript/fonts/roboto/roboto-bold-webfont.ttf 119 bytes {0} [built]
53.79     [10] ./app/javascript/fonts/roboto/roboto-bold-webfont.svg 119 bytes {0} [built]
53.79     [11] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff2 123 bytes {0} [built]
53.79     [12] ./app/javascript/fonts/roboto/roboto-medium-webfont.woff 122 bytes {0} [built]
53.79     [13] ./app/javascript/fonts/roboto/roboto-medium-webfont.ttf 121 bytes {0} [built]
53.79     [14] ./app/javascript/fonts/roboto/roboto-medium-webfont.svg 121 bytes {0} [built]
53.79     [15] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff2 124 bytes {0} [built]
53.79     [16] ./app/javascript/fonts/roboto/roboto-regular-webfont.woff 123 bytes {0} [built]
53.79     [25] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/mastodon-light.scss 902 KiB {0} [built]
53.79         + 11 hidden modules
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/styles/tangerineui-purple.scss:
53.79     Entrypoint mini-css-extract-plugin = *
53.79     [0] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/tangerineui-purple.scss 244 bytes {0} [built] [failed] [1 error]
53.79
53.79     ERROR in ./app/javascript/styles/tangerineui-purple.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/tangerineui-purple.scss)
53.79     Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
53.79     SassError: expected "{".
53.79       ╷
53.79     1 │ 404: Not Found
53.79       │               ^
53.79       ╵
53.79       app/javascript/styles/tangerineui-purple.scss 1:15  root stylesheet
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!app/javascript/styles/tangerineui.scss:
53.79     Entrypoint mini-css-extract-plugin = *
53.79     [0] ./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/tangerineui.scss 237 bytes {0} [built] [failed] [1 error]
53.79
53.79     ERROR in ./app/javascript/styles/tangerineui.scss (./node_modules/css-loader/dist/cjs.js??ref--7-1!./node_modules/postcss-loader/dist/cjs.js??ref--7-2!./node_modules/sass-loader/dist/cjs.js??ref--7-3!./app/javascript/styles/tangerineui.scss)
53.79     Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
53.79     SassError: expected "{".
53.79       ╷
53.79     1 │ 404: Not Found
53.79       │               ^
53.79       ╵
53.79       app/javascript/styles/tangerineui.scss 1:15  root stylesheet
53.79 Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--7-1!node_modules/postcss-loader/dist/cjs.js??ref--7-2!node_modules/sass-loader/dist/cjs.js??ref--7-3!node_modules/font-awesome/css/font-awesome.css:
53.79      5 assets
53.79     Entrypoint mini-css-extract-plugin = *
53.79        10 modules
53.79
------
```

**Comment by vmstan** [comment]
This was an error in my automation script, I didn't catch that the branch name had a v before the number. 🤦‍♂️
